kind: List
apiVersion: v1
items:
- apiVersion: v1  
  kind: PersistentVolume
  metadata:
    name: mongodb-pv-a
  spec:
    capacity: 
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
      - ReadOnlyMany
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /data/mongodb-a
- apiVersion: v1  
  kind: PersistentVolume
  metadata:
    name: mongodb-pv-b
  spec:
    capacity: 
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
      - ReadOnlyMany
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
      path: /data/mongodb-b

